/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cadastro2.java
 *
 * Created on Jan 18, 2010, 11:37:16 PM
 */

package view.client;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.text.DecimalFormat;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import org.netbeans.validation.api.Problems;
import util.component.MoneyField;
import com.avaje.ebean.Ebean;
import java.awt.AWTKeyStroke;
import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.text.JTextComponent;
import mark.utils.bean.IntFormatter;
import mark.utils.bean.MoneyFormatter;
import mark.utils.bind.Binder;
import model.Client;
import model.Phone;
import org.netbeans.validation.api.Problem;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationListener;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Lucas
 */
public class Cadastro extends javax.swing.JDialog {
ValidationGroup validationGroup ;
Binder binder;
    private Client client;

    /** Creates new form Cadastro */
    public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        initComponents();
//        ValidationPanel validationPanel = new ValidationPanel();
//        apelido.setName("[name:nickName]");
//        diaPagamento.setName("[name:paymentDay][fmt:int]");
//        endereco.setName("[name:address]");
//        nomeCompleto.setName("[name:name]");
//        referencia.setName("[name:reference]");
        binder = new Binder(fieldsPanel,Client.class,new IntFormatter(),new MoneyFormatter());
        //validationPanel.setInnerComponent(jPanel1);
        validationGroup = validationPanel.getValidationGroup();
        for (Component c : fieldsPanel.getComponents())
            if (c instanceof JTextComponent) validationGroup.add((JTextComponent)c,Validators.REQUIRE_NON_EMPTY_STRING);
        this.pack();
        this.setLocationRelativeTo(null);
        client = new Client();
    }

    public Cadastro(java.awt.Frame parent, boolean modal, Client client) {
        this(parent, modal);
        this.client = client;
        binder.updateView(client);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel2 = new JPanel();
        buttonsPanel = new JPanel();
        cancelar = new JButton();
        cadastrar = new JButton();
        labelsPanel = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel7 = new JLabel();
        jLabel5 = new JLabel();
        jLabel1 = new JLabel();
        fieldsPanel = new JPanel();
        apelido = new JTextField();
        referencia = new JTextField();
        jScrollPane1 = new JScrollPane();
        endereco = new JTextArea();
        nomeCompleto = new JTextField();
        diaPagamento = new JFormattedTextField();
        moneyField1 = new MoneyField(0.0f);
        validationPanel = new ValidationPanel();
        phonesPanel = new JPanel();
        telefone3 = new JFormattedTextField();
        telefone2 = new JFormattedTextField();
        telefone1 = new JFormattedTextField();
        jLabel6 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente"); // NOI18N
        setName("Form"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new AbsoluteLayout());

        buttonsPanel.setName("buttonsPanel"); // NOI18N
        buttonsPanel.setLayout(new GridLayout(1, 0, 40, 0));

        cancelar.setText("Cancelar"); // NOI18N
        cancelar.setName("cancelar"); // NOI18N
        cancelar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelar);

        cadastrar.setText("Cadastrar"); // NOI18N
        cadastrar.setName("cadastrar"); // NOI18N
        cadastrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        cadastrar.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                cadastrarKeyPressed(evt);
            }
        });
        buttonsPanel.add(cadastrar);

        jPanel2.add(buttonsPanel, new AbsoluteConstraints(145, 431, -1, -1));

        labelsPanel.setName("labelsPanel"); // NOI18N
        labelsPanel.setLayout(new GridBagLayout());

        jLabel2.setText("Nome Completo:"); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 0, 0, 0);
        labelsPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Apelido:"); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(17, 0, 0, 0);
        labelsPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Referência:");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(17, 0, 0, 0);
        labelsPanel.add(jLabel4, gridBagConstraints);

        jLabel7.setText("Dia Pagamento:");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(17, 0, 0, 0);
        labelsPanel.add(jLabel7, gridBagConstraints);

        jLabel5.setText("Endereço:");
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(17, 0, 40, 0);
        labelsPanel.add(jLabel5, gridBagConstraints);

        jLabel1.setText("Saldo Devedor:");
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new Insets(17, 0, 0, 0);
        labelsPanel.add(jLabel1, gridBagConstraints);

        jPanel2.add(labelsPanel, new AbsoluteConstraints(29, 12, -1, -1));

        fieldsPanel.setName("fieldsPanel"); // NOI18N
        fieldsPanel.setLayout(new GridBagLayout());

        apelido.setName("[name:nickName]");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 234;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 12, 0, 12);
        fieldsPanel.add(apelido, gridBagConstraints);

        referencia.setName("[name:reference]");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 234;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 12, 0, 12);
        fieldsPanel.add(referencia, gridBagConstraints);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        endereco.setColumns(20);
        endereco.setRows(5);
        endereco.setName("[name:address]");
        jScrollPane1.setViewportView(endereco);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(12, 12, 12, 12);
        fieldsPanel.add(jScrollPane1, gridBagConstraints);

        nomeCompleto.setName("[name:name]");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 234;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 12, 0, 12);
        fieldsPanel.add(nomeCompleto, gridBagConstraints);

        diaPagamento.setName("[name:paymentDay][fmt:int]");
        diaPagamento.setValue(1);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 12, 0, 0);
        fieldsPanel.add(diaPagamento, gridBagConstraints);

        moneyField1.setName("[name:saldo][fmt:money]");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new Insets(12, 12, 0, 0);
        fieldsPanel.add(moneyField1, gridBagConstraints);

        jPanel2.add(fieldsPanel, new AbsoluteConstraints(139, 12, 254, 292));

        validationPanel.setName("validationPanel"); // NOI18N
        jPanel2.add(validationPanel, new AbsoluteConstraints(891, 14, -1, -1));

        phonesPanel.setName("phonesPanel"); // NOI18N
        phonesPanel.setLayout(new GridBagLayout());

        telefone3.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#"))));
        telefone3.setName("telefone3"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 20, 18, 24);
        phonesPanel.add(telefone3, gridBagConstraints);

        telefone2.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#"))));
        telefone2.setName("telefone2"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 20, 0, 24);
        phonesPanel.add(telefone2, gridBagConstraints);

        telefone1.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#"))));
        telefone1.setName("telefone1"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 20, 0, 24);
        phonesPanel.add(telefone1, gridBagConstraints);

        jLabel6.setText("Telefones:");
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        phonesPanel.add(jLabel6, gridBagConstraints);

        jPanel2.add(phonesPanel, new AbsoluteConstraints(29, 326, -1, -1));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 384, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 466, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        Problem problem = validationGroup.validateAll();
        if (problem != null) return;
        binder.updateModel(client);
        for (Component t : phonesPanel.getComponents()) {
            if (t instanceof JFormattedTextField) {
                JFormattedTextField telefone = (JFormattedTextField) t;
                if (!telefone.getText().isEmpty()) {
                    Phone p = new Phone((Long) telefone.getValue(), client);
                    client.addPhone(p);
                }
            }
        }
        Ebean.save(client);
        this.dispose();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void cadastrarKeyPressed(KeyEvent evt) {//GEN-FIRST:event_cadastrarKeyPressed

}//GEN-LAST:event_cadastrarKeyPressed

    private void cancelarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        client = null;
        this.dispose();
}//GEN-LAST:event_cancelarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField apelido;
    private JPanel buttonsPanel;
    private JButton cadastrar;
    private JButton cancelar;
    private JFormattedTextField diaPagamento;
    private JTextArea endereco;
    private JPanel fieldsPanel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JPanel labelsPanel;
    private MoneyField moneyField1;
    private JTextField nomeCompleto;
    private JPanel phonesPanel;
    private JTextField referencia;
    private JFormattedTextField telefone1;
    private JFormattedTextField telefone2;
    private JFormattedTextField telefone3;
    private ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables

    void updateView(Client client) {
        this.client = client;
        binder.updateView(client);
    }

}
