/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientDetails.java
 *
 * Created on Jan 30, 2010, 2:26:05 PM
 */

package view.client;

import java.util.Observable;
import java.util.Observer;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.Client;
import model.Negotiation;
import util.component.NegotiationHistoryTable;
import util.component.ProductsTable;

/**
 *
 * @author bem
 */
public class ClientDetails extends javax.swing.JDialog implements Observer{
    Client client;
    Cadastro cadastro;
    /** Creates new form ClientDetails */
    public ClientDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        client = new Client();
        findOrNewClientPanel1.addObserver(this);
        findOrNewClientPanel1.addObserver(this.negotiationHistoryTable1);
        cadastro = new Cadastro(parent, modal);
        clientPanel.add(cadastro.getContentPane());
        pack();
        setLocationRelativeTo(null);
        negotiationHistoryTable1.getTable().getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    Negotiation n = negotiationHistoryTable1.getSelectedItem();
                    if (n != null) productsTable1.setData(n);
                    else productsTable1.getTableModel().clear();
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findOrNewClientPanel1 = new FindOrNewClientPanel();
        negotiationHistoryTable1 = new NegotiationHistoryTable();
        productsTable1 = new ProductsTable();
        clientPanel = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        findOrNewClientPanel1.setName("findOrNewClientPanel1"); // NOI18N

        negotiationHistoryTable1.setName("negotiationHistoryTable1"); // NOI18N

        productsTable1.setName("productsTable1"); // NOI18N

        clientPanel.setName("clientPanel"); // NOI18N

        GroupLayout clientPanelLayout = new GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jLabel1.setText("Negociações:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Produtos:");
        jLabel2.setName("jLabel2"); // NOI18N

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(findOrNewClientPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(negotiationHistoryTable1, GroupLayout.PREFERRED_SIZE, 321, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(productsTable1, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(findOrNewClientPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                            .addComponent(productsTable1, 0, 0, Short.MAX_VALUE)
                            .addComponent(negotiationHistoryTable1, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(clientPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientDetails dialog = new ClientDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel clientPanel;
    private FindOrNewClientPanel findOrNewClientPanel1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private NegotiationHistoryTable negotiationHistoryTable1;
    private ProductsTable productsTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (arg != null) {
            client = (Client) arg;
            cadastro.updateView(client);
        }
    }

}
