/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastrarProduto.java
 *
 * Created on Jan 15, 2010, 9:21:28 AM
 */

package view.negotiation;

import com.avaje.ebean.Ebean;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import mark.utils.bean.IntFormatter;
import mark.utils.bean.MoneyFormatter;
import mark.utils.bind.Binder;
import model.Product;
import org.openide.util.NbBundle;
import util.component.MoneyField;

/**
 *
 * @author bem
 */
public class CadastrarProduto extends javax.swing.JDialog {
Binder binder;
Product product;
    /** Creates new form CadastrarProduto */
    public CadastrarProduto(java.awt.Frame parent, boolean modal, Product product) {
        this(parent, modal);
        this.product = product;
    }
    public CadastrarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        binder = new Binder(jPanel1,Product.class,new IntFormatter(),new MoneyFormatter());
        this.product = new Product();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        codeTextfield = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        cadastrarButton = new JButton();
        cancelarButton = new JButton();
        jScrollPane1 = new JScrollPane();
        descriptionTextArea = new JTextArea();
        sellValueFormattedTextField = new MoneyField();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto"); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new GridBagLayout());

        jLabel1.setText("Código:"); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(34, 12, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        codeTextfield.setName("[name:code][fmt:int]"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(32, 12, 0, 0);
        jPanel1.add(codeTextfield, gridBagConstraints);

        jLabel2.setText("Descrição:"); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(53, 12, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Valor de Venda:"); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new Insets(14, 12, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        cadastrarButton.setText("Cadastrar"); // NOI18N
        cadastrarButton.setName("cadastrarButton"); // NOI18N
        cadastrarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(75, 12, 12, 0);
        jPanel1.add(cadastrarButton, gridBagConstraints);

        cancelarButton.setText("Cancelar"); // NOI18N
        cancelarButton.setName("cancelarButton"); // NOI18N
        cancelarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new Insets(75, 31, 12, 0);
        jPanel1.add(cancelarButton, gridBagConstraints);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setName("[name:description]");
        jScrollPane1.setViewportView(descriptionTextArea);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(28, 12, 0, 57);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        sellValueFormattedTextField.setName("[name:sellValue][fmt:money]");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 12, 0, 0);
        jPanel1.add(sellValueFormattedTextField, gridBagConstraints);

        getContentPane().add(jPanel1, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cadastrarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
       binder.updateModel(product);
       Ebean.save(product);
       this.dispose();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarProduto dialog = new CadastrarProduto(new javax.swing.JFrame(), false, new Product());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cadastrarButton;
    private JButton cancelarButton;
    private JTextField codeTextfield;
    private JTextArea descriptionTextArea;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private MoneyField sellValueFormattedTextField;
    // End of variables declaration//GEN-END:variables

}
