/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cadastrarProduto.java
 *
 * Created on Jan 15, 2010, 9:21:28 AM
 */

package view.negotiation;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import mark.utils.bean.IntFormatter;
import mark.utils.bean.MoneyFormatter;
import mark.utils.bind.Binder;
import model.Product;
import org.openide.util.NbBundle;

/**
 *
 * @author bem
 */
public class cadastrarProduto extends javax.swing.JDialog {
Binder binder;
Product product;
    /** Creates new form cadastrarProduto */
    public cadastrarProduto(java.awt.Frame parent, boolean modal, Product product) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        binder = new Binder(jPanel1,Product.class,new IntFormatter(),new MoneyFormatter());
        this.product = product;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        codeTextfield = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        cadastrarButton = new JButton();
        cancelarButton = new JButton();
        sellValueFormattedTextField = new JFormattedTextField();
        jScrollPane1 = new JScrollPane();
        descriptionTextArea = new JTextArea();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(NbBundle.getMessage(cadastrarProduto.class, "cadastrarProduto.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(NbBundle.getMessage(cadastrarProduto.class, "cadastrarProduto.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        codeTextfield.setName("[name:code][fmt:int]"); // NOI18N

        jLabel2.setText(NbBundle.getMessage(cadastrarProduto.class, "cadastrarProduto.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(NbBundle.getMessage(cadastrarProduto.class, "cadastrarProduto.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        cadastrarButton.setText(NbBundle.getMessage(cadastrarProduto.class, "cadastrarProduto.cadastrarButton.text")); // NOI18N
        cadastrarButton.setName("cadastrarButton"); // NOI18N
        cadastrarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText(NbBundle.getMessage(cadastrarProduto.class, "cadastrarProduto.cancelarButton.text")); // NOI18N
        cancelarButton.setName("cancelarButton"); // NOI18N
        cancelarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        sellValueFormattedTextField.setName("[name:sellValue][fmt:money]"); // NOI18N
        sellValueFormattedTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                sellValueFormattedTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setName("[name:description]");
        jScrollPane1.setViewportView(descriptionTextArea);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                            .addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(sellValueFormattedTextField))
                            .addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(codeTextfield, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cadastrarButton)
                        .addGap(33, 33, 33)
                        .addComponent(cancelarButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codeTextfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sellValueFormattedTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(cancelarButton))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellValueFormattedTextFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sellValueFormattedTextFieldActionPerformed
        
    }//GEN-LAST:event_sellValueFormattedTextFieldActionPerformed

    private void cancelarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cadastrarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
       binder.updateModel(product);
       this.dispose();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cadastrarProduto dialog = new cadastrarProduto(new javax.swing.JFrame(), false, new Product());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cadastrarButton;
    private JButton cancelarButton;
    private JTextField codeTextfield;
    private JTextArea descriptionTextArea;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JFormattedTextField sellValueFormattedTextField;
    // End of variables declaration//GEN-END:variables

}
