/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Devolucao.java
 *
 * Created on Jan 26, 2010, 6:31:50 PM
 */

package view.negotiation;

import com.avaje.ebean.Ebean;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.Client;
import model.Negotiation;
import model.Product;
import util.component.NegotiationHistoryTable;
import util.component.ProductsTable;
import view.client.FindOrNewClientPanel;

/**
 *
 * @author bem
 */
public class Devolucao extends javax.swing.JDialog implements Observer{
    private List<Product> removedProducts;
    private Client client;

    /** Creates new form Devolucao */
    public Devolucao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        removedProducts = new ArrayList<Product>();
        initComponents();
        findOrNewClientPanel1.addObserver(this);
        setLocationRelativeTo(null);
        negotiationHistoryTable1.getTable().getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    Negotiation n = negotiationHistoryTable1.getSelectedItem();
                    if (n != null) productsTable.setData(n);
                    else productsTable.getTableModel().clear();
                    removedProducts.clear();
                }
            }
        });
    }

    @Override
    public void update(Observable o, Object arg) {
        if (arg != null){
            client = (Client) arg;
            negotiationHistoryTable1.setData(client);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsTable = new ProductsTable();
        jLabel1 = new JLabel();
        findOrNewClientPanel1 = new FindOrNewClientPanel();
        negotiationHistoryTable1 = new NegotiationHistoryTable();
        jLabel2 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução");
        setName("Form"); // NOI18N

        productsTable.setName("productsTable"); // NOI18N

        jLabel1.setText("Produtos:");
        jLabel1.setName("jLabel1"); // NOI18N

        findOrNewClientPanel1.setName("findOrNewClientPanel1"); // NOI18N

        negotiationHistoryTable1.setName("negotiationHistoryTable1"); // NOI18N

        jLabel2.setText("Operações:");
        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setText("Remover");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(negotiationHistoryTable1, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(findOrNewClientPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(productsTable, GroupLayout.PREFERRED_SIZE, 323, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(626, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findOrNewClientPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(productsTable, GroupLayout.PREFERRED_SIZE, 278, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(negotiationHistoryTable1, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Product p = productsTable.getSelectedItem();
        if (p != null) {
            removedProducts.add(p);
            productsTable.removeItem(p);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Float value = 0.0f;
        for (Product p : removedProducts) value += p.getSellValue();
        Negotiation devolucao = new Negotiation(client, Negotiation.Type.DEVOLUCAO, value);
        devolucao.setProducts(removedProducts);
        client.devolucao(value);
        Ebean.beginTransaction();
        try{
            Ebean.save(devolucao);
            Ebean.saveManyToManyAssociations(devolucao, "products");
            Ebean.save(client);
            Ebean.commitTransaction();
        }
        finally{
            Ebean.endTransaction();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Devolucao dialog = new Devolucao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FindOrNewClientPanel findOrNewClientPanel1;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private NegotiationHistoryTable negotiationHistoryTable1;
    private ProductsTable productsTable;
    // End of variables declaration//GEN-END:variables


}
